import Head from "next/head";
import { Inter } from "@next/font/google";

import type { GetStaticProps, InferGetStaticPropsType } from "next";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { useRouter } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });
type Props = {
  // Add custom props here
};

function Home(_props: InferGetStaticPropsType<typeof getStaticProps>) {
  const router = useRouter();
  const { t } = useTranslation("common");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main data-testid="example">
        <h1 className="header--0">This is an example</h1>
        <p className="text--md text--content">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Dicta autem
          ad et illo
        </p>
        <a
          href="https://google.com"
          className="text--link text--big"
          target="_blank"
          rel="noreferrer"
        >
          {t("hello")}
        </a>
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps<Props> = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale ?? "en", ["common"])),
    },
  };
};

export default Home;
